name: Generate Snake

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create assets folder
        run: mkdir -p assets
      
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to main branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/github-contribution-grid-snake.svg assets/github-contribution-grid-snake-dark.svg
          git commit -m "🐍 Generate Contribution Snake in Assets" || echo "No changes to commit"
          git push
