name: WakaReadme

on:
  schedule:
    # Chạy mỗi 3 giờ một lần (vào phút thứ 0 của mỗi 3 giờ)
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: all_time
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
